export const ACCOUNT = process.env.NEXT_PUBLIC_ACCOUNT;
export const API_DOMAIN = process.env.NEXT_PUBLIC_DOMAIN;
export const STAGE = process.env.NEXT_PUBLIC_STAGE;
export const CHANNEL = process.env.NEXT_PUBLIC_CHANNEL;

export const CART_DOMAIN = process.env.NEXT_PUBLIC_CART_V2_DOMAIN;
export const CART_V2_X_API_KEY = process.env.NEXT_PUBLIC_CART_V2_X_API_KEY;
export const COPILOT_DOMAIN = process.env.NEXT_PUBLIC_COPILOT_DOMAIN;

export const RTPE_DOMAIN = process.env.NEXT_PUBLIC_RTPE_DOMAIN;
export const RTPE_X_API_KEY = process.env.NEXT_PUBLIC_RTPE_X_API_KEY;
export const TENANT_KEY = process.env.NEXT_PUBLIC_TENANT_KEY;

export const NEXT_PUBLIC_CHANNEL_SA = 12;
export const NEXT_PUBLIC_CHANNEL_UAE = 13;
export const NEXT_PUBLIC_CHANNEL_EG = 14;

export const ALGOLIA_SEARCH_INDEX =
  process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_INDEX;
export const ALGOLIA_API_KEY = process.env.NEXT_PUBLIC_ALGOLIA_API_KEY;
export const ALGOLIA_APP_ID = process.env.NEXT_PUBLIC_ALGOLIA_APP_ID;

export const OKTA_DOMAIN_PERSONAL =
  process.env.NEXT_PUBLIC_OKTA_DOMAIN_PERSONAL;
export const OKTA_CLIENT_ID_PERSONAL =
  process.env.NEXT_PUBLIC_OKTA_CLIENT_ID_PERSONAL;
export const OKTA_REDIRECT_URI_PERSONAL =
  process.env.NEXT_PUBLIC_OKTA_REDIRECT_URI_PERSONAL;

export const OKTA_DOMAIN = process.env.NEXT_PUBLIC_OKTA_DOMAIN;
export const OKTA_CLIENT_ID = process.env.NEXT_PUBLIC_OKTA_CLIENT_ID;
export const OKTA_REDIRECT_URI_LOCAL =
  process.env.NEXT_PUBLIC_OKTA_REDIRECT_URI_LOCAL;
export const OKTA_REDIRECT_URI_DEV =
  process.env.NEXT_PUBLIC_OKTA_REDIRECT_URI_DEV;
export const OKTA_REDIRECT_URI_QA =
  process.env.NEXT_PUBLIC_OKTA_REDIRECT_URI_QA;
export const OKTA_REDIRECT_URI_UAT =
  process.env.NEXT_PUBLIC_OKTA_REDIRECT_URI_UAT;

export const OKTA_LOGOUT_REDIRECT_URI_LOCAL =
  process.env.NEXT_PUBLIC_OKTA_LOGOUT_REDIRECT_URI_LOCAL;
export const OKTA_LOGOUT_REDIRECT_URI_DEV =
  process.env.NEXT_PUBLIC_OKTA_LOGOUT_REDIRECT_URI_DEV;
export const OKTA_LOGOUT_REDIRECT_URI_QA =
  process.env.NEXT_PUBLIC_OKTA_LOGOUT_REDIRECT_URI_QA;
export const OKTA_LOGOUT_REDIRECT_URI_UAT =
  process.env.NEXT_PUBLIC_OKTA_LOGOUT_REDIRECT_URI_UAT;
export const UMS_IDENTITY_URL = process.env.NEXT_PUBLIC_UMS_IDENTITY_URL;
export const CUSTOMER_SERVICE_URL =
  process.env.NEXT_PUBLIC_CUSTOMER_SERVICE_SBX_URL;

export const STAMPED_USERNAME = process.env.NEXT_PUBLIC_STAMPED_USERNAME;
export const STAMPED_PASSWORD = process.env.NEXT_PUBLIC_STAMPED_PASSWORD;
export const STAMPED_STORE_HASH_ID = process.env.NEXT_PUBLIC_STAMPED_STORE_HASH;
export const GOOGLE_TRANSLATE_API_KEY =
  process.env.NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY;

export const GET_ORDER = process.env.NEXT_PUBLIC_GET_ORDER;
export const WISHLIST = process.env.NEXT_PUBLIC_GET_WISHLIST;

export const OMS_DOMAIN = process.env.NEXT_PUBLIC_OMS_DOMAIN;

export const CHECKOUT_DOMAIN = process.env.NEXT_PUBLIC_CHECKOUT_DOMAIN_SB;
export const CHECKOUT_SECRET_KEY = process.env.NEXT_PUBLIC_CHECKOUT_SECRET_KEY;
export const CHECKOUT_PUBLIC_KEY = process.env.NEXT_PUBLIC_CHECKOUT_PUBLIC_KEY;

export const LOCATION_ID_AE = process.env.NEXT_PUBLIC_LOCATION_ID_AE;
export const LOCATION_ID_SA = process.env.NEXT_PUBLIC_LOCATION_ID_SA;
export const LOCATION_ID_EG = process.env.NEXT_PUBLIC_LOCATION_ID_EG;
